-- Dodanie autorow
INSERT IGNORE INTO autorzy (nazwa)
VALUES
    ('Adam Mickiewicz'),
    ('Henryk Sienkiewicz'),
    ('Wislawa Szymborska'),
    ('Juliusz Slowacki'),
    ('Maria Dabrowska'),
    ('Zofia Nalkowska'),
    ('Stanislaw Wyspianski'),
    ('Tadeusz Rejtan'),
    ('Jan Kochanowski'),
    ('Bronislaw Pilsudski'),
    ('Wladyslaw Reymont'),
    ('Czeslaw Milosz'),
    ('Jerzy Grotowski'),
    ('Marek Hlasko'),
    ('Janusz Gajos'),
    ('Leopold Tyrmand'),
    ('Ryszard Kapuscinski'),
    ('Jerzy Pilch'),
    ('Olga Tokarczuk'),
    ('Andrzej Sapkowski'),
    ('Adam Asnyk'),
    ('Boleslaw Prus'),
    ('Kazimierz Brandys'),
    ('Krzysztof Kieslowski'),
    ('Piotr Czerwinski'),
    ('Pawel Huelle'),
    ('Ewa Stachniak'),
    ('Mieczyslaw Wojnicz'),
    ('Witold Gombrowicz'),
    ('Zbigniew Herbert'),
    ('Elzbieta Cherezinska'),
    ('Natalia Kadziela'),
    ('Stefan zeromski'),
    ('Roman Dmowski'),
    ('Janusz Korczak'),
    ('Aleksander Kaminski'),
    ('Grzegorz Roman'),
    ('Piotr Szymczak'),
    ('Dariusz Michalski');

