-- Dodanie autorów
INSERT IGNORE INTO autorzy (nazwa)
VALUES
    ('Adam Mickiewicz'),
    ('Henryk Sienkiewicz'),
    ('Wisława Szymborska'),
    ('Juliusz Słowacki'),
    ('Maria Dąbrowska'),
    ('Zofia Nałkowska'),
    ('Stanisław Wyspiański'),
    ('Tadeusz Rejtan'),
    ('Jan Kochanowski'),
    ('Bronisław Piłsudski'),
    ('Władysław Reymont'),
    ('Czesław Miłosz'),
    ('Jerzy Grotowski'),
    ('Marek Hłasko'),
    ('Janusz Gajos'),
    ('Leopold Tyrmand'),
    ('Ryszard Kapuściński'),
    ('Jerzy Pilch'),
    ('Olga Tokarczuk'),
    ('Andrzej Sapkowski'),
    ('Adam Asnyk'),
    ('Bolesław Prus'),
    ('Kazimierz Brandys'),
    ('Krzysztof Kieślowski'),
    ('Piotr Czerwiński'),
    ('Paweł Huelle'),
    ('Ewa Stachniak'),
    ('Mieczysław Wojnicz'),
    ('Witold Gombrowicz'),
    ('Zbigniew Herbert'),
    ('Elżbieta Cherezińska'),
    ('Natalia Kądziela'),
    ('Stefan Żeromski'),
    ('Roman Dmowski'),
    ('Janusz Korczak'),
    ('Aleksander Kamiński'),
    ('Grzegorz Roman'),
    ('Piotr Szymczak'),
    ('Dariusz Michalski');

